[package]
name = "ecjtu_can_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.1.1"

[build-dependencies]
slint-build = "1.1.1"
embed-resource = "2.2.0"